# Generated by Django 4.0.1 on 2022-02-03 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_post_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catigory',
            new_name='Category',
        ),
    ]
